
name = "FefferyAntdMobileComponents"
uuid = "1b08a953-4be3-4667-9a23-3a12f8604b4c"
authors = ["CNFeffery <fefferypzy@gmail.com>"]
version = "0.1.0-rc2"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
