
name = "FefferyAntdMobileComponents"
uuid = "1b08a953-4be3-4667-9a23-847c6f5bdd4c"
authors = ["CNFeffery <fefferypzy@gmail.com>"]
version = "0.0.1-a1"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
